mysql:
  build: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: dev
wp:
  image: bakudankun/wordpress-ja:4.5.2-apache
  links:
    - mysql:mysql
  ports:
    - "8000:80"
  volumes:
    - "${PWD}/wp-content/:/var/www/html/wp-content"
phpmyadmin:
  image: phpmyadmin/phpmyadmin:4.6.2-3
  links:
    - mysql:db
  ports:
    - "8888:80"
  environment:
    PMA_USER: dev
    PMA_PASSWORD: dev
